
#spring.datasource.url=jdbc:postgresql://94.23.58.177:6758/trdp
#spring.datasource.username=trd_usr
#spring.datasource.password=c=W7)Xg-ntFc5e4K


#spring.datasource.url=jdbc:postgresql://localhost:5432/trading_institutional
#spring.datasource.username=trd
#spring.datasource.password=trd

#spring.datasource.url=jdbc:postgresql://trd:5432/meta_trading
#spring.datasource.username=meta_trading_usr
#spring.datasource.password=r2oi5_qzouif9-nqozi


spring:
   main.log-startup-info: false
   main.banner-mode: off 
   datasource:
      hikari.maximum-pool-size: 20
      schema: trading
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate.default_schema: trading
   main.allow-circular-references: true
   task.scheduling.pool.size: 10
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true


logging.level.root: WARN
logging.level.com.trading: INFO
