
#spring.datasource.url=jdbc:postgresql://94.23.58.177:6758/trdp
#spring.datasource.username=trd_usr
#spring.datasource.password=c=W7)Xg-ntFc5e4K


#spring.datasource.url=jdbc:postgresql://localhost:5432/trading_institutional
#spring.datasource.username=trd
#spring.datasource.password=trd

#spring.datasource.url=jdbc:postgresql://trd:5432/meta_trading
#spring.datasource.username=meta_trading_usr
#spring.datasource.password=r2oi5_qzouif9-nqozi


spring:
   datasource:
      hikari.maximum-pool-size: 20
      schema: trading
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate.default_schema: trading
   main.allow-circular-references: true
   task.scheduling.pool.size: 10
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true


meta:
  token: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJmMGRlNjc0ZDRiZjlkY2E5NmFlNGRjYmJiMjU1NDc0MiIsInBlcm1pc3Npb25zIjpbXSwiYWNjZXNzUnVsZXMiOlt7ImlkIjoidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpIiwibWV0aG9kcyI6WyJ0cmFkaW5nLWFjY291bnQtbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1yZXN0LWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1ycGMtYXBpIiwibWV0aG9kcyI6WyJtZXRhYXBpLWFwaTp3czpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1yZWFsLXRpbWUtc3RyZWFtaW5nLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFzdGF0cy1hcGkiLCJtZXRob2RzIjpbIm1ldGFzdGF0cy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoicmlzay1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsicmlzay1tYW5hZ2VtZW50LWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJjb3B5ZmFjdG9yeS1hcGkiLCJtZXRob2RzIjpbImNvcHlmYWN0b3J5LWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtdC1tYW5hZ2VyLWFwaSIsIm1ldGhvZHMiOlsibXQtbWFuYWdlci1hcGk6cmVzdDpkZWFsaW5nOio6KiIsIm10LW1hbmFnZXItYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX1dLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiZjBkZTY3NGQ0YmY5ZGNhOTZhZTRkY2JiYjI1NTQ3NDIiLCJpYXQiOjE2ODc5Mzc5ODJ9.a4ctplYScyEzWA4kM9HRGDuU0pschG3v7JWF1g0aDXqbkFAA8Y90-aYAsH_MbcrMqtYVZ50FUOvu4ZrOGBQ2hMqN2Fw9ayJatnNWiqKPRaPl84zrni6p2gx5foaKMQm47XMow4wnuqAMPQvua1xQQTdQuqPRskpFi6lRPAGLCR7P98n94EGl4LBEtlg44FNzlY0BW46IDAHGuu_5Vpd3KNlwnjaXP_-r8cr3nLSyq9hOHVWFsiQNzStBtfh86H2x5J4U7AlVgT5xshHmx1m7d_gT3N02ay87GAL1oTTTXbNuwwdKYqh_qDTqz52o4_Z1d4s5giVEeC2ZiE8XpLTMWULopicrlMbKj7hgTE0JzBheWtj8Jiho2YLXrs1FdwO8UHwTt4YpUpmErdHgZhwp-gdLTjXXEnKUGm4BzxEadbriIFT3t8TCAtp1Lvy2L1LCcvAvsXFVYGi3pE6nckQZ3hfmbIZwPnLZ8QHwXU--5v31dLe-58bwkbF-bKk_e55C-6bQaHVMTfB-dqVuAAyLSgXOwtf8xnwQXYiRf-YUb3fd9nYfhZOmyW_6zpEKaEZ0WiWkwU8a3_wTx2RS7qkeftkO2vQOBS4vuEhmnoF0hCwpvug0Djo_C1knJr7Z21BIk-PYHvrE__Fvaq2XGrhWXdV7MJDPxDMxY7-JOYkya20
  servers:
    - https://mt-client-api-v1.new-york.agiliumtrade.ai/users/current/accounts/445702b9-3b88-43cc-bd12-c433106c984c
    - https://mt-client-api-v1.new-york.agiliumtrade.ai/users/current/accounts/ba0c3413-bd10-49e8-aec7-81c5bfbbc173
 